version: '3.8'

services:
  eventhubcache:
    image: redis:7.0.15-alpine

  eventhubdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.2

  eventhub.api:
    image: ${DOCKER_REGISTRY-}eventhub-api:${PLATFORM:-windows}-${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile

# network section
networks:
  default:
    name: eventhub
    driver: bridge

# volumes section
volumes:
  sqlserver_data:
    name: sqlserver_data
  elasticsearch_data:
    name: elasticsearch_data