version: '3.8'

services:
  # redis
  redis:
    container_name: redis
    restart: always
    ports:
      - "8000:6379"

  # api sections
  eventhub.api:
    container_name: eventhub.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:DefaultConnection=Server=tcp:eventhubapis.database.windows.net,1433;Initial Catalog=EventHubDatabase;Persist Security Info=False;User ID=EventHubDb;Password=Admin*123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"
      - "ConnectionStrings:DefaultConnection=redis:6379"
    ports:
      - "8002:80"
    restart: always