version: '3.8'

services:
  redis:
      image: redis:alpine
  
  eventhub.api:
    image: ${DOCKER_REGISTRY-}eventhub-api:${PLATFORM:-windows}-${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile

# network section
networks:
  default:
    name: eventhub
    driver: bridge