// <auto-generated />
using System;
using EventHubSolution.BackendServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventHubSolution.BackendServer.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IconImageId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("IconImageId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Command", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.CommandInFunction", b =>
                {
                    b.Property<string>("CommandId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FunctionId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CommandId", "FunctionId");

                    b.HasIndex("FunctionId");

                    b.ToTable("CommandInFunctions");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Conversation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HostId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastMessageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("HostId");

                    b.HasIndex("UserId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.EmailAttachment", b =>
                {
                    b.Property<string>("EmailContentId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AttachmentId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("EmailContentId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("EmailAttachments");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.EmailContent", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("EmailContents");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.EmailLogger", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailContentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ReceiverEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SentEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmailContentId");

                    b.ToTable("EmailLoggers");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Event", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CoverImageId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventCycleType")
                        .HasColumnType("int");

                    b.Property<int>("EventPaymentType")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTrash")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NumberOfFavourites")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfShares")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfSoldTickets")
                        .HasColumnType("int");

                    b.Property<double?>("Promotion")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CoverImageId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.EventCategory", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EventId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CategoryId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("EventCategories");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.EventSubImage", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ImageId");

                    b.ToTable("EventSubImages");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.FavouriteEvent", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EventId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("FavouriteEvents");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.FileStorage", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileContainer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FileStorages");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Function", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Invitation", b =>
                {
                    b.Property<string>("InviterId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("InvitedId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EventId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("InviterId", "InvitedId", "EventId");

                    b.HasIndex("EventId");

                    b.HasIndex("InvitedId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Label", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.LabelInEvent", b =>
                {
                    b.Property<string>("LabelId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EventId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("LabelId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("LabelInEvents");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.LabelInUser", b =>
                {
                    b.Property<string>("LabelId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("LabelId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("LabelInUsers");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Message", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AudioId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImageId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VideoId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AudioId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("EventId");

                    b.HasIndex("ImageId");

                    b.HasIndex("UserId");

                    b.HasIndex("VideoId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Payment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentSessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TicketQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserPaymentMethodId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserPaymentMethodId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.PaymentItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("TicketTypeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("TotalPrice")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("TicketTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentItems");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.PaymentMethod", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MethodLogoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MethodLogoId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Permission", b =>
                {
                    b.Property<string>("FunctionId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CommandId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("FunctionId", "RoleId", "CommandId");

                    b.HasIndex("CommandId");

                    b.HasIndex("RoleId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Reason", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Reasons");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Review", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Ticket", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TicketNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TicketTypeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("TicketTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.TicketType", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NumberOfSoldTickets")
                        .HasColumnType("int");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("TicketTypes");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("NumberOfCreatedEvents")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfFavourites")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfFolloweds")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfFollowers")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.UserFollower", b =>
                {
                    b.Property<string>("FollowerId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FollowedId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("FollowerId", "FollowedId");

                    b.HasIndex("FollowedId");

                    b.ToTable("UserFollowers");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.UserPaymentMethod", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CheckoutContent")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MethodId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentAccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentAccountQRCodeId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MethodId");

                    b.HasIndex("PaymentAccountQRCodeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPaymentMethods");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Role", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasDiscriminator().HasValue("Role");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Category", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Event", null)
                        .WithMany("Categories")
                        .HasForeignKey("EventId");

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.FileStorage", "IconImage")
                        .WithMany()
                        .HasForeignKey("IconImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IconImage");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.CommandInFunction", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Command", "Command")
                        .WithMany("CommandInFunctions")
                        .HasForeignKey("CommandId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Function", "Function")
                        .WithMany("CommandInFunctions")
                        .HasForeignKey("FunctionId")
                        .IsRequired();

                    b.Navigation("Command");

                    b.Navigation("Function");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Conversation", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Event", "Event")
                        .WithMany("Conversations")
                        .HasForeignKey("EventId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", "Host")
                        .WithMany("HostConversations")
                        .HasForeignKey("HostId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", "User")
                        .WithMany("UserConversations")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Host");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.EmailAttachment", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.FileStorage", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.EmailContent", "EmailContent")
                        .WithMany("EmailAttachments")
                        .HasForeignKey("EmailContentId")
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("EmailContent");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.EmailContent", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Event", "Event")
                        .WithOne("EmailContent")
                        .HasForeignKey("EventHubSolution.BackendServer.Data.Entities.EmailContent", "EventId")
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.EmailLogger", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.EmailContent", "EmailContent")
                        .WithMany("EmailLoggers")
                        .HasForeignKey("EmailContentId")
                        .IsRequired();

                    b.Navigation("EmailContent");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Event", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.FileStorage", "CoverImage")
                        .WithMany()
                        .HasForeignKey("CoverImageId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", "Creator")
                        .WithMany("Events")
                        .HasForeignKey("CreatorId")
                        .IsRequired();

                    b.Navigation("CoverImage");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.EventCategory", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Category", "Category")
                        .WithMany("EventCategories")
                        .HasForeignKey("CategoryId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Event", "Event")
                        .WithMany("EventCategories")
                        .HasForeignKey("EventId")
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.EventSubImage", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Event", "Event")
                        .WithMany("EventSubImages")
                        .HasForeignKey("EventId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.FileStorage", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.FavouriteEvent", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Event", "Event")
                        .WithMany("FavouriteEvents")
                        .HasForeignKey("EventId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", "User")
                        .WithMany("FavouriteEvents")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Function", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Function", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Invitation", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Event", "Event")
                        .WithMany("Invitations")
                        .HasForeignKey("EventId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", "Invited")
                        .WithMany("Inviteds")
                        .HasForeignKey("InvitedId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", "Inviter")
                        .WithMany("Inviters")
                        .HasForeignKey("InviterId")
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Invited");

                    b.Navigation("Inviter");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.LabelInEvent", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Event", "Event")
                        .WithMany("LabelInEvents")
                        .HasForeignKey("EventId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Label", "Label")
                        .WithMany("LabelInEvents")
                        .HasForeignKey("LabelId")
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.LabelInUser", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Label", "Label")
                        .WithMany("LabelInUsers")
                        .HasForeignKey("LabelId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", "User")
                        .WithMany("LabelInUsers")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Label");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Message", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.FileStorage", "Audio")
                        .WithMany()
                        .HasForeignKey("AudioId");

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Event", "Event")
                        .WithMany("Messages")
                        .HasForeignKey("EventId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.FileStorage", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.FileStorage", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId");

                    b.Navigation("Audio");

                    b.Navigation("Conversation");

                    b.Navigation("Event");

                    b.Navigation("Image");

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Payment", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Event", "Event")
                        .WithMany("Payments")
                        .HasForeignKey("EventId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.UserPaymentMethod", "UserPaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("UserPaymentMethodId")
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");

                    b.Navigation("UserPaymentMethod");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.PaymentItem", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Event", "Event")
                        .WithMany("PaymentItems")
                        .HasForeignKey("EventId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Payment", "Payment")
                        .WithMany("PaymentItems")
                        .HasForeignKey("PaymentId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.TicketType", "TicketType")
                        .WithMany("PaymentItems")
                        .HasForeignKey("TicketTypeId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", "User")
                        .WithMany("PaymentItems")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Payment");

                    b.Navigation("TicketType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.PaymentMethod", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.FileStorage", "MethodLogo")
                        .WithMany()
                        .HasForeignKey("MethodLogoId")
                        .IsRequired();

                    b.Navigation("MethodLogo");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Permission", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Command", "Command")
                        .WithMany("Permissions")
                        .HasForeignKey("CommandId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Function", "Function")
                        .WithMany("Permissions")
                        .HasForeignKey("FunctionId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .IsRequired();

                    b.Navigation("Command");

                    b.Navigation("Function");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Reason", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Event", "Event")
                        .WithMany("Reasons")
                        .HasForeignKey("EventId")
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Review", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Event", "Event")
                        .WithMany("Reviews")
                        .HasForeignKey("EventId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Ticket", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Payment", "Payment")
                        .WithMany("Tickets")
                        .HasForeignKey("PaymentId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.TicketType", "TicketType")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketTypeId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Payment");

                    b.Navigation("TicketType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.TicketType", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.Event", "Event")
                        .WithMany("TicketTypes")
                        .HasForeignKey("EventId")
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.User", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.FileStorage", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.UserFollower", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", "Followed")
                        .WithMany("Followeds")
                        .HasForeignKey("FollowedId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", "Follower")
                        .WithMany("Followers")
                        .HasForeignKey("FollowerId")
                        .IsRequired();

                    b.Navigation("Followed");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.UserPaymentMethod", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.PaymentMethod", "Method")
                        .WithMany("UserPaymentMethods")
                        .HasForeignKey("MethodId")
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.FileStorage", "PaymentAccountQRCode")
                        .WithMany()
                        .HasForeignKey("PaymentAccountQRCodeId");

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", "User")
                        .WithMany("UserPaymentMethods")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Method");

                    b.Navigation("PaymentAccountQRCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EventHubSolution.BackendServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Category", b =>
                {
                    b.Navigation("EventCategories");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Command", b =>
                {
                    b.Navigation("CommandInFunctions");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.EmailContent", b =>
                {
                    b.Navigation("EmailAttachments");

                    b.Navigation("EmailLoggers");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Event", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Conversations");

                    b.Navigation("EmailContent");

                    b.Navigation("EventCategories");

                    b.Navigation("EventSubImages");

                    b.Navigation("FavouriteEvents");

                    b.Navigation("Invitations");

                    b.Navigation("LabelInEvents");

                    b.Navigation("Messages");

                    b.Navigation("PaymentItems");

                    b.Navigation("Payments");

                    b.Navigation("Reasons");

                    b.Navigation("Reviews");

                    b.Navigation("TicketTypes");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Function", b =>
                {
                    b.Navigation("CommandInFunctions");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Label", b =>
                {
                    b.Navigation("LabelInEvents");

                    b.Navigation("LabelInUsers");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Payment", b =>
                {
                    b.Navigation("PaymentItems");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.PaymentMethod", b =>
                {
                    b.Navigation("UserPaymentMethods");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.TicketType", b =>
                {
                    b.Navigation("PaymentItems");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.User", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("FavouriteEvents");

                    b.Navigation("Followeds");

                    b.Navigation("Followers");

                    b.Navigation("HostConversations");

                    b.Navigation("Inviteds");

                    b.Navigation("Inviters");

                    b.Navigation("LabelInUsers");

                    b.Navigation("Messages");

                    b.Navigation("PaymentItems");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");

                    b.Navigation("Tickets");

                    b.Navigation("UserConversations");

                    b.Navigation("UserPaymentMethods");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.UserPaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EventHubSolution.BackendServer.Data.Entities.Role", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
